databases:
  - name: medicare-db
    databaseName: medicare
    user: medicare_user
    plan: free

services:
  - type: web
    name: medicare
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: medicare-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: "False"
